language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1
  - 1.3
  - nightly

matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true

jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script: julia --project=docs --color=yes -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
