## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1.3
  - nightly
notifications:
  email: false
git:
  depth: 99999999

jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: osx
      script: julia --project=docs --color=yes -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip

